/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'Outfit', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'Courier New', 'monospace'],
      },
      colors: {
        'brand-blue': '#3b82f6',
        'brand-purple': '#8b5cf6',
        'brand-indigo': '#6366f1',
      },
      animation: {
        'fade-in': 'fade-in 0.35s ease-out both',
        'slide-up': 'slide-up 0.3s cubic-bezier(0.16, 1, 0.3, 1) both',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  // Safelist dynamic classes generated by JS/JSX
  safelist: [
    'text-blue-400', 'text-indigo-400', 'text-purple-400', 'text-orange-400',
    'text-rose-400', 'text-green-400', 'text-emerald-400', 'text-red-400',
    'text-cyan-400', 'text-amber-400', 'text-teal-400', 'text-yellow-400',
    'from-blue-400', 'from-indigo-400', 'from-purple-400', 'from-orange-400',
    'from-rose-400', 'from-green-400', 'from-red-400',
    'to-indigo-400', 'to-purple-400', 'to-rose-400', 'to-orange-400',
    'border-blue-500', 'border-indigo-500', 'border-purple-500',
    'border-b-2', 'border-indigo-400', 'border-red-400', 'border-orange-400',
    'bg-gray-800/50', 'bg-gray-900/30', 'bg-gray-900/50',
    'bg-gradient-to-r', 'bg-clip-text', 'text-transparent',
    'animate-spin', 'rounded-full', 'h-12', 'w-12',
    'grid-cols-1', 'md:grid-cols-2', 'gap-8',
    'fixed', 'inset-0', 'z-50',
    'max-w-3xl', 'max-w-md', 'mx-auto',
    'space-y-4', 'space-y-2', 'gap-2', 'gap-3', 'gap-4',
    'flex', 'items-center', 'justify-between', 'justify-end', 'justify-center',
    'p-4', 'p-6', 'p-8', 'px-4', 'py-3', 'mt-1', 'mt-2', 'mt-4', 'mb-6', 'mb-8',
    'text-xs', 'text-sm', 'text-xl', 'text-2xl', 'text-3xl',
    'font-bold', 'font-medium', 'font-mono',
    'text-white', 'text-gray-100', 'text-gray-300', 'text-gray-400', 'text-gray-500',
    'col-span-full', 'opacity-0', 'group-hover:opacity-100', 'transition-opacity',
    'transition-colors', 'transition-transform', 'transition-all',
    'hover:bg-gray-700', 'hover:bg-gray-600',
    'rounded-lg', 'rounded-full', 'border', 'border-gray-700', 'border-red-500',
    'outline-none', 'resize-none', 'break-all',
    'w-full', 'h-32', 'h-48', 'h-64', 'w-32', 'h-32',
    'object-cover', 'relative', 'absolute',
    '-bottom-2', '-right-2',
    'group', 'group-hover:scale-110', 'scale-110',
  ],
  plugins: [],
}
