services:
  - type: web
    name: tapid-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERVE_STATIC
        value: "false"
      - key: DB_HOST
        value: mysql-33b99771-dootisaha-2325.j.aivencloud.com
      - key: DB_PORT
        value: "12183"
      - key: DB_USER
        value: avnadmin
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        value: tapid
      - key: JWT_SECRET
        generateValue: true
      - key: DEVICE_API_KEY
        value: tapid-esp32-device-key-2026
      - key: CORS_ORIGIN
        value: "*"
