import os
import json

structure = {
    "README.md": "# TapID\n\nTap. Verify. Record.\n\nAn IoT-Based Smart RFID Attendance Management System Using ESP32.",
    "LICENSE": "MIT License",
    ".gitignore": "node_modules/\n.env\n*.log",
    "docker-compose.yml": "",
    "package.json": '{\n  "name": "tapid",\n  "version": "1.0.0"\n}',
    "package-lock.json": "",
    ".env.example": "PORT=3000\nDB_HOST=localhost\nDB_USER=root\nDB_PASS=\nDB_NAME=tapid\nJWT_SECRET=secret",
    "docs/Project_Report.pdf": None,
    "docs/IEEE_Paper.pdf": None,
    "docs/User_Manual.pdf": None,
    "docs/Installation_Guide.pdf": None,
    "docs/API_Documentation.pdf": None,
    "docs/Literature_Survey.pdf": None,
    "docs/SRS_Document.pdf": None,
    "docs/Architecture_Diagram.png": None,
    "docs/ER_Diagram.png": None,
    "docs/DFD_Level0.png": None,
    "docs/DFD_Level1.png": None,
    "docs/Flowchart.png": None,
    "docs/Circuit_Diagram.png": None,
    "docs/Presentation.pptx": None,
    "firmware/esp32/main.ino": "// Main Entry",
    "firmware/esp32/config.h": "",
    "firmware/esp32/wifi_manager.cpp": "",
    "firmware/esp32/wifi_manager.h": "",
    "firmware/esp32/rfid_reader.cpp": "",
    "firmware/esp32/rfid_reader.h": "",
    "firmware/esp32/buzzer.cpp": "",
    "firmware/esp32/buzzer.h": "",
    "firmware/esp32/led.cpp": "",
    "firmware/esp32/led.h": "",
    "firmware/esp32/api_client.cpp": "",
    "firmware/esp32/api_client.h": "",
    "firmware/esp32/attendance.cpp": "",
    "firmware/esp32/attendance.h": "",
    "firmware/esp32/offline_queue.cpp": "",
    "firmware/esp32/offline_queue.h": "",
    "firmware/esp32/secrets.h": "",
    "firmware/libraries/.gitkeep": "",
    "backend/package.json": '{\n  "name": "tapid-backend",\n  "version": "1.0.0"\n}',
    "backend/server.js": "",
    "backend/app.js": "",
    "backend/config/database.js": "",
    "backend/config/jwt.js": "",
    "backend/config/config.js": "",
    "backend/config/logger.js": "",
    "backend/routes/auth.routes.js": "",
    "backend/routes/attendance.routes.js": "",
    "backend/routes/student.routes.js": "",
    "backend/routes/faculty.routes.js": "",
    "backend/routes/classroom.routes.js": "",
    "backend/routes/subject.routes.js": "",
    "backend/routes/session.routes.js": "",
    "backend/routes/admin.routes.js": "",
    "backend/routes/device.routes.js": "",
    "backend/controllers/auth.controller.js": "",
    "backend/controllers/attendance.controller.js": "",
    "backend/controllers/student.controller.js": "",
    "backend/controllers/faculty.controller.js": "",
    "backend/controllers/session.controller.js": "",
    "backend/controllers/admin.controller.js": "",
    "backend/controllers/device.controller.js": "",
    "backend/middleware/auth.middleware.js": "",
    "backend/middleware/role.middleware.js": "",
    "backend/middleware/jwt.middleware.js": "",
    "backend/middleware/validation.middleware.js": "",
    "backend/middleware/error.middleware.js": "",
    "backend/middleware/rate_limit.js": "",
    "backend/services/attendance.service.js": "",
    "backend/services/student.service.js": "",
    "backend/services/faculty.service.js": "",
    "backend/services/device.service.js": "",
    "backend/services/report.service.js": "",
    "backend/services/email.service.js": "",
    "backend/services/analytics.service.js": "",
    "backend/models/Student.js": "",
    "backend/models/Faculty.js": "",
    "backend/models/Attendance.js": "",
    "backend/models/Subject.js": "",
    "backend/models/Classroom.js": "",
    "backend/models/Session.js": "",
    "backend/models/Device.js": "",
    "backend/utils/logger.js": "",
    "backend/utils/jwt.js": "",
    "backend/utils/validator.js": "",
    "backend/utils/response.js": "",
    "backend/utils/helper.js": "",
    "backend/uploads/.gitkeep": "",
    "frontend/package.json": '{\n  "name": "tapid-frontend",\n  "version": "1.0.0"\n}',
    "frontend/public/favicon.ico": None,
    "frontend/public/logo.png": None,
    "frontend/public/manifest.json": "",
    "frontend/src/assets/.gitkeep": "",
    "frontend/src/components/Navbar/.gitkeep": "",
    "frontend/src/components/Sidebar/.gitkeep": "",
    "frontend/src/components/Tables/.gitkeep": "",
    "frontend/src/components/Charts/.gitkeep": "",
    "frontend/src/components/Cards/.gitkeep": "",
    "frontend/src/components/Loader/.gitkeep": "",
    "frontend/src/pages/Login/.gitkeep": "",
    "frontend/src/pages/Dashboard/.gitkeep": "",
    "frontend/src/pages/Attendance/.gitkeep": "",
    "frontend/src/pages/Students/.gitkeep": "",
    "frontend/src/pages/Faculty/.gitkeep": "",
    "frontend/src/pages/Subjects/.gitkeep": "",
    "frontend/src/pages/Classrooms/.gitkeep": "",
    "frontend/src/pages/Reports/.gitkeep": "",
    "frontend/src/pages/Devices/.gitkeep": "",
    "frontend/src/pages/Settings/.gitkeep": "",
    "frontend/src/services/.gitkeep": "",
    "frontend/src/hooks/.gitkeep": "",
    "frontend/src/context/.gitkeep": "",
    "frontend/src/utils/.gitkeep": "",
    "frontend/src/routes/.gitkeep": "",
    "frontend/src/styles/.gitkeep": "",
    "frontend/src/App.jsx": "",
    "frontend/src/index.jsx": "",
    "database/schema.sql": "",
    "database/seed.sql": "",
    "database/procedures.sql": "",
    "database/triggers.sql": "",
    "database/indexes.sql": "",
    "database/backup/.gitkeep": "",
    "api/Postman_Collection.json": "",
    "api/Swagger.yaml": "",
    "api/API_Testing.pdf": None,
    "hardware/Circuit_Diagram.fzz": None,
    "hardware/Circuit_Diagram.pdf": None,
    "hardware/PCB/.gitkeep": "",
    "hardware/STL/.gitkeep": "",
    "hardware/Enclosure/.gitkeep": "",
    "hardware/Components.xlsx": None,
    "tests/firmware/.gitkeep": "",
    "tests/backend/.gitkeep": "",
    "tests/frontend/.gitkeep": "",
    "tests/integration/.gitkeep": "",
    "tests/security/.gitkeep": "",
    "deployment/nginx/.gitkeep": "",
    "deployment/docker/.gitkeep": "",
    "deployment/pm2/.gitkeep": "",
    "deployment/scripts/.gitkeep": "",
    "media/screenshots/.gitkeep": "",
    "media/demo_video/.gitkeep": "",
    "media/poster/.gitkeep": "",
    ".github/workflows/ci.yml": ""
}

base_dir = "d:\\TapID"

for path, content in structure.items():
    full_path = os.path.join(base_dir, path)
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    if content is not None:
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(content)
    else:
        # Create empty binary/pdf/png/fzz/xlsx/ico files
        with open(full_path, "wb") as f:
            pass

print("Project structure scaffolded successfully in", base_dir)
